[package]
name = "lockfree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "simple_spsc_queue"
path = "examples/simple_spsc_queue.rs"
doc = false
